import express from 'express';
import fs from 'fs';
import path from 'path';
import React from 'react';
import ReactDOMServer from 'react-dom/server';
import { StaticRouter } from 'react-router-dom/server';
import { Helmet } from 'react-helmet';
import { createProxyMiddleware } from 'http-proxy-middleware';
import axios from 'axios'; // Import Axios for sitemap fetching
import { WP_BASE, getImage } from '../src/apiServices/wpApi.ts';
import App from '../src/App.tsx';

const PORT = 8081;
const WORDPRESS_TIMEOUT_MS = 10000;
const app = express();
app.use(express.json()); // Enable JSON body parsing
const router = express.Router();

// 1. Resolve path to dist folder
const distPath = path.resolve(__dirname, '../dist');
const indexFile = path.join(distPath, 'index.html');
console.log('Server - __dirname:', __dirname);
console.log('Server - distPath resolved to:', distPath);

// Debug Middleware
router.use((req, res, next) => {
  console.log('Request URL:', req.url);
  if (req.url.startsWith('/assets/')) {
    const filePath = path.join(distPath, req.url);
    const assetsDir = path.join(distPath, 'assets');
    console.log('Checking file:', filePath);
    console.log('File exists:', fs.existsSync(filePath));
    if (fs.existsSync(assetsDir)) {
      console.log('Assets dir contents sample:', fs.readdirSync(assetsDir).slice(0, 5));
      console.log('Does clutch.png exist in dir listing?', fs.readdirSync(assetsDir).includes('clutch.png'));
    } else {
      console.log('Assets dir NOT found at:', assetsDir);
    }
  }
  next();
});

// 2. Serve static assets
router.use(express.static(distPath, { index: false, maxAge: '30d' }));

// ---------------------------------------------------------------------------
// CMS API ENDPOINTS
// ---------------------------------------------------------------------------

const DATA_DIR = path.resolve(__dirname, '../src/data');

function formatWpDate(value) {
  return new Date(value).toLocaleDateString('en-US', {
    day: '2-digit',
    month: 'long',
    year: 'numeric',
  });
}

function mapPostSummary(post) {
  return {
    id: post.id,
    slug: post.slug,
    title: post.title.rendered,
    date: formatWpDate(post.date),
    image: getImage(post),
    category: post._embedded?.['wp:term']?.[0]?.[0]?.name || 'General',
    linkpath: `/blog/${post.slug}/`,
  };
}

function stripOldTOC(html = '') {
  return html
    .replace(/<div id="ez-toc-container[\s\S]*?<\/div>/gi, '')
    .replace(/<nav[\s\S]*?<\/nav>/gi, '')
    .replace(/<ul[\s\S]*?ez-toc-list[\s\S]*?<\/ul>/gi, '')
    .trim();
}

function mapPostDetail(post) {
  const finalImage = getImage(post);

  return {
    id: post.id,
    slug: post.slug,
    title: post.title.rendered,
    content: stripOldTOC(post.content?.rendered || ''),
    date: formatWpDate(post.date),
    image: finalImage,
    og_image: finalImage,
    author: post._embedded?.author?.[0]?.name || 'BytechSol Team',
    category: post._embedded?.['wp:term']?.[0]?.[0]?.name || 'General',
    excerpt: post.excerpt,
  };
}

router.get('/api/cms/:type', (req, res) => {
  const { type } = req.params;
  const filePath = path.join(DATA_DIR, `${type}Data.json`);

  if (!fs.existsSync(filePath)) {
    return res.status(404).json({ error: 'Data not found' });
  }

  const data = fs.readFileSync(filePath, 'utf-8');
  res.json(JSON.parse(data));
});

router.post('/api/cms/:type', (req, res) => {
  const { type } = req.params;
  const filePath = path.join(DATA_DIR, `${type}Data.json`);

  try {
    fs.writeFileSync(filePath, JSON.stringify(req.body, null, 2));
    res.json({ success: true });
  } catch (err) {
    res.status(500).json({ error: 'Failed to save data' });
  }
});

// ---------------------------------------------------------------------------
// A. PROXY: Fixes the "/cms" Redirect Issue
// ---------------------------------------------------------------------------
// This sends any request starting with /cms directly to your WordPress host.
// If your WP is on the same server (Hostinger), it might be on port 80 or 8080.
// If this doesn't work, change target to 'http://127.0.0.1:80' or your domain.
// router.use(
//   '/cms',
//   createProxyMiddleware({
//     target: 'https://bytechsol.com/cms', // Or 'http://127.0.0.1:8080/cms' if local
//     changeOrigin: true,
//     // We do NOT rewrite the path because WP expects /cms to be there
//   })
// );

// ---------------------------------------------------------------------------
// B. SITEMAP: Fixes the "/blog" SEO Issue
// ---------------------------------------------------------------------------
// We create a custom sitemap that fetches WP data but acts like it's React data.
router.get('/sitemap.xml', async (req, res) => {
  try {
    // 1. Fetch the sitemap generated by Yoast/WP
    const wpSitemapUrl = 'https://bytechsol.com/cms/post-sitemap.xml';
    const response = await axios.get(wpSitemapUrl, { timeout: WORDPRESS_TIMEOUT_MS });

    let sitemapData = response.data;

    // 2. THE MAGIC FIX: Replace '/cms/' with '/blog/' in the XML content
    // This tricks Google into thinking the posts live at /blog/slug
    sitemapData = sitemapData.replace(/\/cms\//g, '/blog/');

    // 3. Send the modified XML
    res.header('Content-Type', 'application/xml');
    res.send(sitemapData);

  } catch (error) {
    console.error('Error generating sitemap:', error);
    res.status(500).send('Error generating sitemap');
  }
});

// ---------------------------------------------------------------------------
// C. SSR HANDLER (React App)
// ---------------------------------------------------------------------------
router.get(/(.*)/, (req, res) => {
  if (!fs.existsSync(indexFile)) {
    console.error('❌ Missing dist/index.html');
    return res.status(500).send("Build missing. Please run 'npm run build' first.");
  }

  fs.readFile(indexFile, 'utf-8', async (err, data) => {
    if (err) {
      console.error('❌ Error reading index.html:', err);
      return res.status(500).send("Server Error");
    }

    try {
      const AppComponent = App.default || App;
      const isBlogIndexRoute = req.url === '/blog/' || req.url === '/blog';
      const initialWpData = {
        blogPosts: null,
        blogPost: null,
        relatedPosts: null,
        slug: null,
      };

      if (isBlogIndexRoute) {
        try {
          const response = await axios.get(`${WP_BASE}/posts?_embed=true&per_page=100`, {
            timeout: WORDPRESS_TIMEOUT_MS,
          });
          initialWpData.blogPosts = response.data.map(mapPostSummary);
        } catch (fetchErr) {
          console.error('âŒ SSR Blog List Fetch Error:', fetchErr.message);
        }
      }

      globalThis.__INITIAL_WP_DATA__ = initialWpData;
      console.log(`⚡ Rendering content for: ${req.url}`);

      const appHtml = ReactDOMServer.renderToString(
        <StaticRouter location={req.url}>
          <AppComponent />
        </StaticRouter>
      );

      const helmet = Helmet.renderStatic();

      let titleString = helmet.title.toString();
      let metaString = helmet.meta.toString();

      // --- SERVER-SIDE DATA FETCHING FOR BLOGS ---
      // If we are on a blog page, fetch the specific post data to fix SEO tags.
      if (req.url.startsWith('/blog/')) {
        try {
          // Extract slug: /blog/my-post-title/ -> my-post-title
          const slug = req.url.split('/blog/')[1].split('?')[0].replace(/\/$/, '');

          if (slug) {
            console.log(`🔍 SSR fetching blog data for slug: ${slug}`);
            const apiUrl = `${WP_BASE}/posts?slug=${slug}&_embed=true`;
            const response = await axios.get(apiUrl, { timeout: WORDPRESS_TIMEOUT_MS });

            if (response.data && response.data.length > 0) {
              const post = response.data[0];
              const mappedPost = mapPostDetail(post);
              initialWpData.blogPost = mappedPost;
              initialWpData.slug = slug;
              const safeTitle = post.title.rendered;
              // Strip HTML from excerpt and limit length
              const cleanExcerpt = post.excerpt.rendered
                .replace(/<[^>]*>?/gm, '')
                .replace(/\n/g, ' ')
                .trim()
                .substring(0, 160);

              console.log(`✅ SSR found blog: "${safeTitle}"`);

              // Overwrite/Inject Title
              titleString = `<title>${safeTitle} | BytechSol Blog</title>`;

              // Prepend description meta tag (Helmet might be empty due to async component loading)
              metaString = `<meta name="description" content="${cleanExcerpt}" /> ${metaString}`;

              try {
                const relatedResponse = await axios.get(`${WP_BASE}/posts?_embed=true&per_page=100`, {
                  timeout: WORDPRESS_TIMEOUT_MS,
                });
                initialWpData.relatedPosts = relatedResponse.data
                  .map(mapPostSummary)
                  .filter((item) => item.id !== mappedPost.id)
                  .slice(0, 3);
              } catch (relatedErr) {
                console.error('âŒ SSR Related Blogs Fetch Error:', relatedErr.message);
              }
            } else {
              console.log(`⚠️ SSR blog not found for slug: ${slug}`);
            }
          }
        } catch (fetchErr) {
          console.error('❌ SSR Blog Fetch Error:', fetchErr.message);
        }
      }
      // -------------------------------------------

      const finalHtml = data
        .replace('<div id="root"></div>', `<div id="root">${appHtml}</div>`)
        .replace(/<title>.*<\/title>/, titleString)
        .replace(
          '</head>',
          `${metaString} ${helmet.link.toString()} ${helmet.script.toString()} <script>window.__INITIAL_WP_DATA__ = ${JSON.stringify(initialWpData).replace(/</g, '\\u003c')};</script> </head>`
        );

      delete globalThis.__INITIAL_WP_DATA__;
      return res.send(finalHtml);

    } catch (renderErr) {
      delete globalThis.__INITIAL_WP_DATA__;
      console.error('❌ SSR Rendering Error:', renderErr);
      return res.send(data);
    }
  });
});

app.use(router);

app.listen(PORT, () => {
  console.log(`✅ Server running on http://localhost:${PORT}`);
});
