import express from 'express';
import fs from 'fs';
import path from 'path';
import React from 'react';
import ReactDOMServer from 'react-dom/server';
import { StaticRouter } from 'react-router-dom/server';
import { Helmet } from 'react-helmet';
import { createProxyMiddleware } from 'http-proxy-middleware';
import axios from 'axios'; // Import Axios for sitemap fetching
import App from '../src/App.tsx';

const PORT = 8081;
const app = express();
app.use(express.json()); // Enable JSON body parsing
const router = express.Router();

// 1. Resolve path to dist folder
const distPath = path.resolve(__dirname, '../dist');
const indexFile = path.join(distPath, 'index.html');
console.log('Server - __dirname:', __dirname);
console.log('Server - distPath resolved to:', distPath);

// Debug Middleware
router.use((req, res, next) => {
  console.log('Request URL:', req.url);
  if (req.url.startsWith('/assets/')) {
    const filePath = path.join(distPath, req.url);
    const assetsDir = path.join(distPath, 'assets');
    console.log('Checking file:', filePath);
    console.log('File exists:', fs.existsSync(filePath));
    if (fs.existsSync(assetsDir)) {
      console.log('Assets dir contents sample:', fs.readdirSync(assetsDir).slice(0, 5));
      console.log('Does clutch.png exist in dir listing?', fs.readdirSync(assetsDir).includes('clutch.png'));
    } else {
      console.log('Assets dir NOT found at:', assetsDir);
    }
  }
  next();
});

// 2. Serve static assets
router.use(express.static(distPath, { index: false, maxAge: '30d' }));

// ---------------------------------------------------------------------------
// CMS API ENDPOINTS
// ---------------------------------------------------------------------------

const DATA_DIR = path.resolve(__dirname, '../src/data');

router.get('/api/cms/:type', (req, res) => {
  const { type } = req.params;
  const filePath = path.join(DATA_DIR, `${type}Data.json`);

  if (!fs.existsSync(filePath)) {
    return res.status(404).json({ error: 'Data not found' });
  }

  const data = fs.readFileSync(filePath, 'utf-8');
  res.json(JSON.parse(data));
});

router.post('/api/cms/:type', (req, res) => {
  const { type } = req.params;
  const filePath = path.join(DATA_DIR, `${type}Data.json`);

  try {
    fs.writeFileSync(filePath, JSON.stringify(req.body, null, 2));
    res.json({ success: true });
  } catch (err) {
    res.status(500).json({ error: 'Failed to save data' });
  }
});

// ---------------------------------------------------------------------------
// A. PROXY: Fixes the "/cms" Redirect Issue
// ---------------------------------------------------------------------------
// This sends any request starting with /cms directly to your WordPress host.
// If your WP is on the same server (Hostinger), it might be on port 80 or 8080.
// If this doesn't work, change target to 'http://127.0.0.1:80' or your domain.
// router.use(
//   '/cms',
//   createProxyMiddleware({
//     target: 'https://bytechsol.com/cms', // Or 'http://127.0.0.1:8080/cms' if local
//     changeOrigin: true,
//     // We do NOT rewrite the path because WP expects /cms to be there
//   })
// );

// ---------------------------------------------------------------------------
// B. SITEMAP: Fixes the "/blog" SEO Issue
// ---------------------------------------------------------------------------
// We create a custom sitemap that fetches WP data but acts like it's React data.
router.get('/sitemap.xml', async (req, res) => {
  try {
    // 1. Fetch the sitemap generated by Yoast/WP
    const wpSitemapUrl = 'https://bytechsol.com/cms/post-sitemap.xml';
    const response = await axios.get(wpSitemapUrl);

    let sitemapData = response.data;

    // 2. THE MAGIC FIX: Replace '/cms/' with '/blog/' in the XML content
    // This tricks Google into thinking the posts live at /blog/slug
    sitemapData = sitemapData.replace(/\/cms\//g, '/blog/');

    // 3. Send the modified XML
    res.header('Content-Type', 'application/xml');
    res.send(sitemapData);

  } catch (error) {
    console.error('Error generating sitemap:', error);
    res.status(500).send('Error generating sitemap');
  }
});

// ---------------------------------------------------------------------------
// C. SSR HANDLER (React App)
// ---------------------------------------------------------------------------
router.get(/(.*)/, (req, res) => {
  if (!fs.existsSync(indexFile)) {
    console.error('❌ Missing dist/index.html');
    return res.status(500).send("Build missing. Please run 'npm run build' first.");
  }

  fs.readFile(indexFile, 'utf-8', async (err, data) => {
    if (err) {
      console.error('❌ Error reading index.html:', err);
      return res.status(500).send("Server Error");
    }

    try {
      const AppComponent = App.default || App;
      console.log(`⚡ Rendering content for: ${req.url}`);

      const appHtml = ReactDOMServer.renderToString(
        <StaticRouter location={req.url}>
          <AppComponent />
        </StaticRouter>
      );

      const helmet = Helmet.renderStatic();

      let titleString = helmet.title.toString();
      let metaString = helmet.meta.toString();

      // --- SERVER-SIDE DATA FETCHING FOR BLOGS ---
      // If we are on a blog page, fetch the specific post data to fix SEO tags.
      if (req.url.startsWith('/blog/')) {
        try {
          // Extract slug: /blog/my-post-title/ -> my-post-title
          const slug = req.url.split('/blog/')[1].split('?')[0].replace(/\/$/, '');

          if (slug) {
            console.log(`🔍 SSR fetching blog data for slug: ${slug}`);
            const apiUrl = `https://bytechsol.com/cms/wp-json/wp/v2/posts?slug=${slug}`;
            const response = await axios.get(apiUrl);

            if (response.data && response.data.length > 0) {
              const post = response.data[0];
              const safeTitle = post.title.rendered;
              // Strip HTML from excerpt and limit length
              const cleanExcerpt = post.excerpt.rendered
                .replace(/<[^>]*>?/gm, '')
                .replace(/\n/g, ' ')
                .trim()
                .substring(0, 160);

              console.log(`✅ SSR found blog: "${safeTitle}"`);

              // Overwrite/Inject Title
              titleString = `<title>${safeTitle} | BytechSol Blog</title>`;

              // Prepend description meta tag (Helmet might be empty due to async component loading)
              metaString = `<meta name="description" content="${cleanExcerpt}" /> ${metaString}`;
            } else {
              console.log(`⚠️ SSR blog not found for slug: ${slug}`);
            }
          }
        } catch (fetchErr) {
          console.error('❌ SSR Blog Fetch Error:', fetchErr.message);
        }
      }
      // -------------------------------------------

      const finalHtml = data
        .replace('<div id="root"></div>', `<div id="root">${appHtml}</div>`)
        .replace(/<title>.*<\/title>/, titleString)
        .replace('</head>', `${metaString} ${helmet.link.toString()} ${helmet.script.toString()} </head>`);

      return res.send(finalHtml);

    } catch (renderErr) {
      console.error('❌ SSR Rendering Error:', renderErr);
      return res.send(data);
    }
  });
});

app.use(router);

app.listen(PORT, () => {
  console.log(`✅ Server running on http://localhost:${PORT}`);
});